// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIq5dvNrktsxP1dBeAUAH8flCrZ8e1Fk',
    appId: '1:210588025207:web:b66422cffc8ae025c4e172',
    messagingSenderId: '210588025207',
    projectId: 'minimal-b1a04',
    authDomain: 'minimal-b1a04.firebaseapp.com',
    storageBucket: 'minimal-b1a04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9IcGtGWytHRGMHdORBjTiyjqp6CdnGEQ',
    appId: '1:210588025207:android:b086e61a3d2d8d4bc4e172',
    messagingSenderId: '210588025207',
    projectId: 'minimal-b1a04',
    storageBucket: 'minimal-b1a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxp2R2BQ-w_Jc8OVPqZus51OdlnI4946Q',
    appId: '1:210588025207:ios:faf09adfdbe2355ec4e172',
    messagingSenderId: '210588025207',
    projectId: 'minimal-b1a04',
    storageBucket: 'minimal-b1a04.appspot.com',
    iosBundleId: 'com.example.minimal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxp2R2BQ-w_Jc8OVPqZus51OdlnI4946Q',
    appId: '1:210588025207:ios:3da890264046c87ec4e172',
    messagingSenderId: '210588025207',
    projectId: 'minimal-b1a04',
    storageBucket: 'minimal-b1a04.appspot.com',
    iosBundleId: 'com.example.minimal.RunnerTests',
  );
}
